### ISSUE TITLE
widget issues

### ISSUE THREAD

**Issue by SpaceWebb** [cgHome/homey.homepageExtender#1]
This app looks very nice... i love to use it. Installation went well, and as far as i can see, it works...
at least i got the provided example of homey working.

But... i have tried now 3 widgets, and non of them is working...
What am i doing wrong?

![image](https://github.com/cgHome/homey.homepageExtender/assets/132126716/c7c45386-14f3-4d99-b7e2-8c4a7adfe55e)

for example the proxmox widget:
- My Servers:
    - Proxmox: 
        widget:
            type: proxmox
            url: https://192.168.2.70:8006
            username: api@pam!homepage
            password: 5a5xxxxxxxxxxx
            node: pve-1 # optional
            mappings:
                - field: vms
                  label: vms
                  format: text

**Comment by cgHome** [comment]
[You already got the answer](https://community.homey.app/t/app-pro-homepage-extender-v1-0/104370/18)
